#pragma once
#include <array>
#include "runtime/ctr_ipc.h"
#include "runtime/ctr_shared_memory.h"

namespace lego::ctr {
// ErrCodes::FirstInitialization(519), GX(10), Success summary/level.
inline constexpr Result kResultGspFirstInitialization = 0x00002A07U;
inline constexpr std::uint32_t kGspRelaySlots = 4;

// Ownership and relay registration only. No GPU commands, interrupts, vblank,
// framebuffer effects or hardware timing are generated by registration.
class GspGpuService final : public IpcService {
public:
    GspGpuService() : shared_(std::make_shared<SharedState>()) {}
    Result CreateSessionHandler(std::shared_ptr<IpcService>* out) override {
        if (!out) return kResultInvalidPointer;
        for (std::uint32_t slot=0; slot<kGspRelaySlots; ++slot) {
            if (!shared_->slots[slot].expired()) continue;
            auto handler=std::shared_ptr<GspGpuService>(new GspGpuService(shared_,slot));
            shared_->slots[slot]=handler->identity_;
            *out=std::move(handler);
            return kResultSuccess;
        }
        return kResultMaxConnectionsReached;
    }
    bool CanHandle(const IpcCommandBuffer& command) const noexcept override {
        if (!identity_) return false; // Registration endpoint is never a client.
        if (command[0]==IpcMakeHeader(0x0013,1,2))
            return (command[1]&~1U)==0 && command[2]==IpcCopyHandleDesc();
        return shared_->owner.expired() &&
               command[0]==IpcMakeHeader(0x0016,1,2) && command[1]==0 &&
               command[2]==IpcCopyHandleDesc();
    }
    Result Handle(IpcRouter& router,Kernel& kernel,GuestMemory&,ThreadObject& thread,
                  IpcCommandBuffer& command) override {
        if(!CanHandle(command))return kResultNotFound;
        if (IpcCommandId(command[0])==0x0013) {
            const auto event=std::dynamic_pointer_cast<EventObject>(kernel.handles().Get(command[3]));
            if (!event) return kResultInvalidHandle;
            ::lego::ctr::Handle handle=0;
            const Result result=kernel.handles().Create(&handle,shared_->memory);
            if (result!=kResultSuccess) return result;
            // All fallible validation/allocation precedes registration. This is
            // a copy: retaining the event does not close or signal the caller's handle.
            const Result reply=shared_->first_registration ? kResultGspFirstInitialization : kResultSuccess;
            identity_->event=event;
            identity_->flags=command[1];
            identity_->registered=true;
            shared_->first_registration=false;
            command.fill(0); command[0]=IpcMakeHeader(0x0013,2,2);
            command[1]=reply; command[2]=identity_->slot;
            command[3]=IpcCopyHandleDesc(); command[4]=handle;
            return kResultSuccess;
        }
        const auto process=std::dynamic_pointer_cast<ProcessObject>(kernel.handles().Get(command[3]));
        if(!process)return kResultInvalidHandle;
        if(process!=kernel.current_process()) {
            router.RequestHostStop("GSP AcquireRight for another process is unsupported");
            return kResultSuccess;
        }
        identity_->process_id=process->process_id;
        identity_->client_thread_id=thread.thread_id;
        shared_->owner=identity_;
        command.fill(0);command[0]=IpcMakeHeader(0x0016,1,0);command[1]=kResultSuccess;
        return kResultSuccess;
    }
    [[nodiscard]] bool rights_held() const noexcept { return !shared_->owner.expired(); }
    [[nodiscard]] bool owns_rights() const noexcept { return identity_ && shared_->owner.lock()==identity_; }
    [[nodiscard]] std::optional<std::uint32_t> owner_process_id() const noexcept {
        if(const auto owner=shared_->owner.lock())return owner->process_id;
        return std::nullopt;
    }
    [[nodiscard]] std::optional<std::uint32_t> active_client_thread_id() const noexcept {
        if(const auto owner=shared_->owner.lock())return owner->client_thread_id;
        return std::nullopt;
    }
    [[nodiscard]] std::optional<std::uint32_t> relay_slot() const noexcept {
        return identity_ ? std::optional(identity_->slot) : std::nullopt;
    }
    [[nodiscard]] bool registered() const noexcept { return identity_ && identity_->registered; }
    [[nodiscard]] std::uint32_t relay_flags() const noexcept { return identity_ ? identity_->flags : 0; }
    [[nodiscard]] std::shared_ptr<EventObject> relay_event() const noexcept { return identity_ ? identity_->event : nullptr; }
    [[nodiscard]] std::shared_ptr<ServiceSharedMemoryObject> shared_memory() const noexcept { return shared_->memory; }
    [[nodiscard]] bool first_registration_pending() const noexcept { return shared_->first_registration; }
private:
    struct SessionIdentity {
        std::uint32_t slot{},process_id{},client_thread_id{},flags{};
        bool registered{};
        std::shared_ptr<EventObject> event;
    };
    struct SharedState {
        std::weak_ptr<SessionIdentity> owner;
        std::array<std::weak_ptr<SessionIdentity>,kGspRelaySlots> slots;
        std::shared_ptr<ServiceSharedMemoryObject> memory=std::make_shared<ServiceSharedMemoryObject>();
        bool first_registration{true};
    };
    GspGpuService(std::shared_ptr<SharedState> shared,std::uint32_t slot)
        : shared_(std::move(shared)),identity_(std::make_shared<SessionIdentity>()) {identity_->slot=slot;}
    std::shared_ptr<SharedState> shared_;
    // Final client-session reference retires its event, slot and ownership;
    // duplicated handles retain the SAME identity, not another numeric slot.
    std::shared_ptr<SessionIdentity> identity_;
};
} // namespace lego::ctr
